name: Daily Market Briefing

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 오전 9시 (KST = UTC+9)
  workflow_dispatch:

jobs:
  send-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run telegram sender
        run: python send.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

